version: '3.7'

services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    build:
      context: back
      dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    restart: always
    depends_on: 
      - db 
    environment: 
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tennis?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root     
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  app-client:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "80:4200" 
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  
      
  db:
    build: 
      context: /Users/also/Desktop/tennis/db
      dockerfile: Dockerfile
    restart: always  
    ports:  
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: tennis
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend  

# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    